# -*- coding: utf-8 -*-

#

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Archivo(object):
    def setupUi(self, Archivo):
        Archivo.setObjectName("Archivo")
        Archivo.resize(827, 623)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Archivo.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Archivo)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(50, 90, 711, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 30, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Dni = QtWidgets.QLabel(self.centralwidget)
        self.Dni.setGeometry(QtCore.QRect(60, 150, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Dni.setFont(font)
        self.Dni.setObjectName("Dni")
        self.apellido = QtWidgets.QLabel(self.centralwidget)
        self.apellido.setGeometry(QtCore.QRect(60, 240, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.apellido.setFont(font)
        self.apellido.setObjectName("apellido")
        self.nombre = QtWidgets.QLabel(self.centralwidget)
        self.nombre.setGeometry(QtCore.QRect(400, 240, 50, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nombre.setFont(font)
        self.nombre.setObjectName("nombre")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(50, 470, 711, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.botonAcep = QtWidgets.QPushButton(self.centralwidget)
        self.botonAcep.setGeometry(QtCore.QRect(170, 500, 120, 40))
        self.botonAcep.setObjectName("botonAcep")
        self.botonSalir = QtWidgets.QPushButton(self.centralwidget)
        self.botonSalir.setGeometry(QtCore.QRect(520, 500, 120, 40))
        self.botonSalir.setObjectName("botonSalir")
        self.textoDni = QtWidgets.QLineEdit(self.centralwidget)
        self.textoDni.setGeometry(QtCore.QRect(130, 150, 140, 30))
        self.textoDni.setObjectName("textoDni")
        self.textoApe = QtWidgets.QLineEdit(self.centralwidget)
        self.textoApe.setGeometry(QtCore.QRect(130, 240, 140, 30))
        self.textoApe.setObjectName("textoApe")
        self.textoNom = QtWidgets.QLineEdit(self.centralwidget)
        self.textoNom.setGeometry(QtCore.QRect(500, 240, 140, 30))
        self.textoNom.setObjectName("textoNom")
        Archivo.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Archivo)
        self.statusbar.setObjectName("statusbar")
        Archivo.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(Archivo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 21))
        self.menubar.setObjectName("menubar")
        self.menuGesti_n = QtWidgets.QMenu(self.menubar)
        self.menuGesti_n.setObjectName("menuGesti_n")
        Archivo.setMenuBar(self.menubar)
        self.actionSalir = QtWidgets.QAction(Archivo)
        self.actionSalir.setCheckable(True)
        self.actionSalir.setObjectName("actionSalir")
        self.menuGesti_n.addAction(self.actionSalir)
        self.menuGesti_n.addSeparator()
        self.menubar.addAction(self.menuGesti_n.menuAction())

        self.retranslateUi(Archivo)
        QtCore.QMetaObject.connectSlotsByName(Archivo)

    def retranslateUi(self, Archivo):
        _translate = QtCore.QCoreApplication.translate
        Archivo.setWindowTitle(_translate("Archivo", "MainWindow"))
        self.label.setText(_translate("Archivo", "GESTIÓN DE CLIENTES"))
        self.Dni.setText(_translate("Archivo", "DNI"))
        self.apellido.setText(_translate("Archivo", "Apellido"))
        self.nombre.setText(_translate("Archivo", "Nombre"))
        self.botonAcep.setText(_translate("Archivo", "Aceptar"))
        self.botonSalir.setText(_translate("Archivo", "Salir"))
        self.menuGesti_n.setTitle(_translate("Archivo", "Archivo"))
        self.actionSalir.setText(_translate("Archivo", "Salir"))
        self.actionSalir.setShortcut(_translate("Archivo", "Alt+S"))
